name: Build
on:
  push:
    tags:
      - "web-v*"

jobs:      
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v20

      - name: Build app
        run: nix build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          # Artifact name
          name: asd.scr
          # A file, directory or wildcard pattern that describes what to upload
          path: "{{ github.workspace }} /artifact" 
          # The desired behavior if no files are found using the provided path.
     
